name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Ruff on main.py
        uses: astral-sh/ruff-action@v3
        with:
          # Specify only the single file here
          src: "./main.py"
